#!/usr/bin/env bash
# 07-remote-access.sh — SSH server, Screen Sharing, Tailscale

set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "$SCRIPT_DIR/scripts/lib/log.sh"
source "$SCRIPT_DIR/scripts/lib/check.sh"
source "$SCRIPT_DIR/scripts/lib/prompt.sh"
source "$SCRIPT_DIR/scripts/lib/backup.sh"

require_macos

log_section "Remote Access"

SSH_AUTH_KEYS="$HOME/.ssh/authorized_keys"
TAILSCALE_HOSTNAME=$(scutil --get ComputerName 2>/dev/null || hostname)

# --- SSH Server ---
log_step 1 "SSH server (Remote Login)"
SSH_STATUS=$(systemsetup -getremotelogin 2>/dev/null || echo "")
if echo "$SSH_STATUS" | grep -qi "on"; then
  log_success "SSH server already enabled"
else
  log_info "Enabling SSH server..."
  if [[ "$DRY_RUN" != "true" ]]; then
    sudo systemsetup -setremotelogin on
    log_success "SSH server enabled"
  fi
fi

# --- SSH authorized_keys ---
log_step 2 "SSH authorized_keys"
if [[ "$DRY_RUN" != "true" ]]; then
  mkdir -p "$HOME/.ssh"
  chmod 700 "$HOME/.ssh"
  touch "$SSH_AUTH_KEYS"
  chmod 600 "$SSH_AUTH_KEYS"

  while prompt_yn "Add an authorized public key (for Chromebook, iPad, or friend)?"; do
    DEVICE=$(prompt_text "Device label (e.g. chromebook, ipad, friend-name):")
    KEY=$(prompt_text "Paste public key (ssh-ed25519 ...):")
    if [[ -n "$KEY" ]]; then
      echo "# $DEVICE" >> "$SSH_AUTH_KEYS"
      echo "$KEY" >> "$SSH_AUTH_KEYS"
      log_success "Key added for: $DEVICE"
    fi
  done
fi

# --- Screen Sharing (VNC) ---
log_step 3 "Screen Sharing / VNC"
if [[ "$DRY_RUN" != "true" ]]; then
  sudo launchctl load -w /System/Library/LaunchDaemons/com.apple.screensharing.plist 2>/dev/null || \
  sudo launchctl enable system/com.apple.screensharing 2>/dev/null || true
  log_success "Screen Sharing enabled"
fi

# --- Tailscale ---
log_step 4 "Tailscale"
if brew_installed tailscale; then
  log_success "Tailscale already installed"
else
  log_info "Installing Tailscale..."
  [[ "$DRY_RUN" != "true" ]] && brew install --cask tailscale
fi

if [[ "$DRY_RUN" != "true" ]]; then
  if ! tailscale status &>/dev/null; then
    if prompt_yn "Connect Tailscale now? (requires auth key or browser login)"; then
      TAILSCALE_KEY=$(prompt_secret "Tailscale auth key (or press Enter to use browser):")
      if [[ -n "$TAILSCALE_KEY" ]]; then
        tailscale up --authkey="$TAILSCALE_KEY"
      else
        tailscale up
      fi
    fi
  else
    log_success "Tailscale already connected"
    TAILSCALE_HOSTNAME=$(tailscale status --json 2>/dev/null | jq -r '.Self.DNSName // empty' | sed 's/\.$//') || true
  fi
fi

# --- Write ~/.ssh/config entry for VS Code Remote SSH ---
log_step 5 "SSH config for VS Code Remote SSH"
if [[ "$DRY_RUN" != "true" ]]; then
  SSH_CONFIG="$HOME/.ssh/config"
  mkdir -p "$HOME/.ssh" && chmod 700 "$HOME/.ssh"
  touch "$SSH_CONFIG" && chmod 600 "$SSH_CONFIG"
  if grep -q "Host mac-mini" "$SSH_CONFIG" 2>/dev/null; then
    log_success "~/.ssh/config entry for 'mac-mini' already exists"
  else
    backup_file "$SSH_CONFIG"
    cat >> "$SSH_CONFIG" <<SSHEOF

Host mac-mini
  HostName $TAILSCALE_HOSTNAME
  User $(whoami)
  IdentityFile ~/.ssh/id_ed25519
  ServerAliveInterval 60
SSHEOF
    log_success "~/.ssh/config entry written (Host mac-mini → $TAILSCALE_HOSTNAME)"
  fi
fi

# --- Generate docs/remote-access.md ---
log_step 6 "Generating docs/remote-access.md"
if [[ "$DRY_RUN" == "true" ]]; then
  log_info "[DRY RUN] Would generate docs/remote-access.md"
else
  mkdir -p "$SCRIPT_DIR/docs"
  cat > "$SCRIPT_DIR/docs/remote-access.md" <<EOF
# Remote Access Guide

Generated by \`07-remote-access.sh\` on $(date '+%Y-%m-%d').

## Your Mac

- **Hostname:** $TAILSCALE_HOSTNAME
- **Local SSH:** \`ssh $(whoami)@$(hostname -f 2>/dev/null || hostname)\`
- **Tailscale SSH:** \`ssh $(whoami)@$TAILSCALE_HOSTNAME\`
- **VS Code Remote SSH:** Use Host \`mac-mini\` (configured in ~/.ssh/config)

## From Chromebook (Crostini)

\`\`\`bash
# SSH
ssh $(whoami)@$TAILSCALE_HOSTNAME

# VNC (after installing tigervnc-viewer)
vncviewer $TAILSCALE_HOSTNAME:5900
\`\`\`

## From iPad

| Purpose | App |
|---|---|
| SSH terminal | Blink Shell or Termius |
| VNC / Screen | Screens 5 or Jump Desktop |
| Tailscale | Tailscale (App Store) |

**SSH connection:** Server = \`$TAILSCALE_HOSTNAME\`, Port = 22, Username = \`$(whoami)\`

## Sharing with Friends

1. Have your friend generate an SSH key: \`ssh-keygen -t ed25519\`
2. Add their public key to this Mac: run \`./bootstrap.sh --only remote\` and choose "Add authorized key"
3. Share your Tailscale node name: \`$TAILSCALE_HOSTNAME\`
4. They connect with: \`ssh $(whoami)@$TAILSCALE_HOSTNAME\`

## VS Code Remote SSH

Install "Remote - SSH" extension in VS Code, then:
- Open Command Palette → "Remote-SSH: Connect to Host"
- Select \`mac-mini\` (pre-configured in ~/.ssh/config)
EOF
  log_success "docs/remote-access.md generated"
fi  # end DRY_RUN guard for remote-access.md

log_success "Remote access setup complete"
